# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Publish NuGet

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source files
        uses: actions/checkout@v4

      - name: Retrieve current year
        run: echo "YEAR=$(date +%Y)" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Add private NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/etn-utilities/index.json" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble the project
        run: gradle assemble

      - name: Run the tests
        run: gradle test

      - name: Build with Gradle
        run: ./gradlew releaseTarGz

      - name: Find Kafka zip
        run: find . -name "*kafka*.tgz"

      - name: Extract Kafka package
        run: |
          ARCHIVE_PATH=$(find . -name "kafka_2.13-3.9.0.tgz")
          mkdir -p ./extract/kafka
          tar -xvf $ARCHIVE_PATH -C ./extract/kafka --strip-components=1
      - name: Generate and publish NuGet packages
        run: |
          dotnet pack ./nupkg/kafka.nuspec --no-build --output .
          dotnet nuget push *.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
