# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Publish NuGet

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    # actions/checkout@v4.2.2
    - name: Get source files
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Retrieve current year
      run: echo "YEAR=$(date +%Y)" >> $GITHUB_ENV

    # actions/setup-java@v4.7.0
    - name: Set up JDK 17
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Add private NuGet source
      run: nuget sources Add -Name "github" -Source "https://nuget.pkg.github.com/etn-utilities/index.json" -UserName ${{ github.actor }} -Password ${{ secrets.GITHUB_TOKEN }}
      
    #gradle/setup-gradle@v3.5.0
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b

    - name: Assemble the project
      run: gradle assemble

#    - name: Run the tests
#      run: gradle test
#      continue-on-error: true

    - name: Build with Gradle
      run: ./gradlew releaseTarGz

    - name: Find Kafka zip
      run: find . -name "kafka*.tgz"

    - name: Extract Kafka package
      run: |
        ARCHIVE_PATH=$(find . -name "kafka_2.13-3.9.0.tgz")
        mkdir -p ./extract/kafka
        tar -xvf $ARCHIVE_PATH -C ./extract/kafka --strip-components=1
  
#    - name: Quick glance at extraction
#      run: ls -R ./extract

    - name: Generate and publish NuGet packages
      run: |
        nuget pack ./nupkg/kafka.nuspec -OutputDirectory .
        nuget push *.nupkg -Source github -ApiKey ${{ secrets.GITHUB_TOKEN }} --skip-duplicate